### ISSUE TITLE
Setup linting and style enforcement.

### ISSUE THREAD

**Issue by Alonski** [Alonski/realworld-ember#10]
We should be using ESLint and Prettier +- Standard to format our Javascript.
If we need custom CSS we can use stylelint and stylefmt.
Maybe using SASS instead of plain CSS

**Comment by Alonski** [comment]
In addition to this I am using VSCode and would like to setup our style enforcement there with settings.
@alexlafroscia Does it make sense to enforce using VSCode? Do you use something else?

**Comment by alexlafroscia** [comment]
Definitely *not* interested in enforcing a particular editor... What would that solve? If we want style enforcement (which shouldn't really be necessary since the CSS is pulled from the CDN) then we can set that up as a linter that runs as part of the tests, like ESLint does.

Definitely in favor of ESLint though. Prettier is a good idea too; I like it and it's helpful for projects without a styleguide (and I don't want to write a whole styleguide for this).

**Comment by Alonski** [comment]
All right. How do you have any experience adding prettier into the build pipeline for Ember?
I want handlebar formatting to be consistent as well as JS.
For CSS I understand that we probably won't need to format it.

**Comment by alexlafroscia** [comment]
The only tool I know for HBS style checking is `ember-template-lint`

https://github.com/rwjblue/ember-cli-template-lint
https://github.com/rwjblue/ember-template-lint

We can set that up if you want, but I'm happy to just do code review for style issues too.

***

I have configured prettier+eslint before on a number of projects. Happy to do that here.

**Comment by Alonski** [comment]
Ok cool. I'll look into setting up ember-template-lint

**Comment by alexlafroscia** [comment]
Great. Should just require installing `ember-cli-template-lint`.

I'll set up ESLint + prettier when I get home from work tonight.

**Comment by Alonski** [comment]
Ok cool. Sounds easy enough

**Comment by jamesbrewerdev** [comment]
Howdy! Since #15 got merged, should this issue be closed?

**Comment by Alonski** [comment]
@brwr I want to setup ember-cli-template-lint and then close this 😄

**Comment by jamesbrewerdev** [comment]
Awesome! Thank you for your work!

**Comment by Alonski** [comment]
@brwr Thanks a lot! Once we get more into this I will look for more Ember people to contribute.
@alexlafroscia I tried setting up ember-cli-template-lint but the current builds have errors. 
Waiting for those to resolve before trying again.
https://github.com/rwjblue/ember-cli-template-lint/issues/185

**Comment by alexlafroscia** [comment]
No worries. I'm not really concerned too much with linting the templates (i've never used that plugin before, even) so I'm fine with the ESLint/Prettier setup that we have now, and then just catching issues in the templates through code review.

**Comment by alexlafroscia** [comment]
This issue was moved to gothinkster/ember-realworld-example-app#3
