### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by alexlafroscia** [Alonski/realworld-ember#2]
Since the idea is that this is a canonical Ember app, we should make sure to highlight the awesome testing abilities that Ember brings to the table! First step there is to set up CI to run on each pull request.

**Comment by alexlafroscia** [comment]
I don't have the permissions required to set this up, unfortunately, so @Alonski will have to do that himself since it's his repo.

Should be able to go here and turn it on https://travis-ci.org/Alonski/realworld-ember

Ember comes with the config out-of-the-box, but we should add the status badge to the README.

**Comment by Alonski** [comment]
Seems to be working 😄 
Our first build failed though 😨
